# Generated by Django 4.0.2 on 2022-02-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='breed',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='age',
            new_name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
